#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  6 16:54:55 2019

@author: fubar

This script demonsrates the core underlying principle
of Qt's user-app interaction - the signal - slot mechanism

Signal is any event generated by a Qt object
Slot is the event handler or the action to be performed for a particular signal
connect() is the callback interface between a singal and a slot

Reference : https://build-system.fman.io/pyqt5-tutorial

"""

from PyQt5.QtWidgets import QApplication, QPushButton, QMessageBox
app = QApplication([])
button = QPushButton('Click')   #This is a PushButton widget
#
# Define a slot which allows the signal to be slotted
# (i.e what to do with the signal) when the signal is generated
#
def on_button_clicked():
    alert = QMessageBox()       # set a Message Window
    alert.setText('You clicked the button!')
    alert.exec_()               # hand over the control to the alert window


#
# create a signal to be generated by button widget and
# calling the on_button_clicke() method as a slot
#
button.clicked.connect(on_button_clicked)
#
# show the button
#
button.show()
app.exec_()